CREATE TABLE IF NOT EXISTS crm_settings (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  key TEXT UNIQUE NOT NULL,
  value JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS but allow public access for this local demo context
ALTER TABLE crm_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read settings" ON crm_settings FOR SELECT USING (true);
CREATE POLICY "Public insert settings" ON crm_settings FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update settings" ON crm_settings FOR UPDATE USING (true);
